services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: logsicle-api
    expose:
      - 3005
    environment:
      - PORT=3005
      - DEV=${DEV:-false}

      - DB_DSN=${POSTGRES_DSN}
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=25
      - DB_CONN_MAX_LIFETIME=15m
      - REDIS_URL=${REDIS_DSN}/0
      - REDIS_QUEUE_URL=${REDIS_DSN}/1
      - REDIS_SESSION_URL=${REDIS_DSN}/2

      - CORS_ALLOWED_ORIGINS=$WEB_URL
      - CORS_COOKIE_DOMAIN=${LOGSICLE_DOMAIN}

      - AUTH_ENDPOINT=${AUTH_ENDPOINT}
      - AUTH_APP_ID=${AUTH_APP_ID}
      - AUTH_APP_SECRET=${AUTH_APP_SECRET}

      - API_URL=${API_URL}
      - WEB_URL=${WEB_URL}
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - logsicle-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - PUBLIC_API_URL=${API_URL}
    container_name: logsicle-web
    expose:
      - 3000
    environment:
      - PORT=3000
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - api
    networks:
      - logsicle-network

  migrations:
    # Coolify-specific option to exclude from healthchecks
    exclude_from_hc: true
    build:
      context: ./apps/api
      dockerfile: Dockerfile.migrations
    container_name: logsicle-migrations
    command: [ "migrate", "apply", "--url", "${POSTGRES_DSN}&search_path=public" ]
    restart: "no" # Important: don't restart after completion
    networks:
      - logsicle-network

networks:
  logsicle-network:
    driver: bridge
