services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: logsicle-api
    expose:
      - 3005
    environment:
      - PORT=3005
      - API_URL=${API_URL:-http://localhost:3005}
      - WEB_URL=${WEB_URL:-http://localhost:3000}
      - DB_DSN=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-logsicle}?sslmode=disable
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=25
      - DB_CONN_MAX_LIFETIME=15m
      - REDIS_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SESSION_URL=redis://redis:6379/2
      - CORS_ALLOWED_ORIGINS=${WEB_URL:-http://localhost:3000}
      - CORS_COOKIE_DOMAIN=${SERVICE_COOKIE_DOMAIN}
      - DEV=${DEV:-false}
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - logsicle-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - VITE_API_URL=${API_URL:-http://localhost:3005}
    container_name: logsicle-web
    expose:
      - 3000
    environment:
      - PORT=3000
    depends_on:
      - api
    networks:
      - logsicle-network

  migrations:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.migrations
    container_name: logsicle-migrations
    command: [ "migrate", "apply", "--url", "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-logsicle}?search_path=public&sslmode=disable" ]
    restart: "no" # Important: don't restart after completion
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logsicle-network

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: logsicle-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-logsicle}
    volumes:
      - logsicle_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-logsicle}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - logsicle-network

  redis:
    image: redis:7-alpine
    container_name: logsicle-redis
    volumes:
      - redis_data:/data
    networks:
      - logsicle-network

networks:
  logsicle-network:
    driver: bridge

volumes:
  logsicle_postgres_data:
  redis_data:
