/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthdImport } from './routes/_authd'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignOutImport } from './routes/auth/sign-out'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as AuthdAppImport } from './routes/_authd/_app'
import { Route as AuthdDashboardOnboardingImport } from './routes/_authd/dashboard.onboarding'
import { Route as AuthdAppDashboardIndexImport } from './routes/_authd/_app.dashboard/index'
import { Route as AuthdAppDashboardProjIdIndexImport } from './routes/_authd/_app.dashboard/$projId.index'
import { Route as AuthdAppDashboardProjIdTracesImport } from './routes/_authd/_app.dashboard/$projId.traces'
import { Route as AuthdAppDashboardProjIdSettingsImport } from './routes/_authd/_app.dashboard/$projId.settings'
import { Route as AuthdAppDashboardProjIdLogsImport } from './routes/_authd/_app.dashboard/$projId.logs'
import { Route as AuthdAppDashboardProjIdEventsImport } from './routes/_authd/_app.dashboard/$projId.events'
import { Route as AuthdAppDashboardProjIdAlertsImport } from './routes/_authd/_app.dashboard/$projId.alerts'

// Create/Update Routes

const AuthdRoute = AuthdImport.update({
  id: '/_authd',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignOutRoute = AuthSignOutImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthdAppRoute = AuthdAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthdRoute,
} as any)

const AuthdDashboardOnboardingRoute = AuthdDashboardOnboardingImport.update({
  id: '/dashboard/onboarding',
  path: '/dashboard/onboarding',
  getParentRoute: () => AuthdRoute,
} as any)

const AuthdAppDashboardIndexRoute = AuthdAppDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthdAppRoute,
} as any)

const AuthdAppDashboardProjIdIndexRoute =
  AuthdAppDashboardProjIdIndexImport.update({
    id: '/dashboard/$projId/',
    path: '/dashboard/$projId/',
    getParentRoute: () => AuthdAppRoute,
  } as any)

const AuthdAppDashboardProjIdTracesRoute =
  AuthdAppDashboardProjIdTracesImport.update({
    id: '/dashboard/$projId/traces',
    path: '/dashboard/$projId/traces',
    getParentRoute: () => AuthdAppRoute,
  } as any)

const AuthdAppDashboardProjIdSettingsRoute =
  AuthdAppDashboardProjIdSettingsImport.update({
    id: '/dashboard/$projId/settings',
    path: '/dashboard/$projId/settings',
    getParentRoute: () => AuthdAppRoute,
  } as any)

const AuthdAppDashboardProjIdLogsRoute =
  AuthdAppDashboardProjIdLogsImport.update({
    id: '/dashboard/$projId/logs',
    path: '/dashboard/$projId/logs',
    getParentRoute: () => AuthdAppRoute,
  } as any)

const AuthdAppDashboardProjIdEventsRoute =
  AuthdAppDashboardProjIdEventsImport.update({
    id: '/dashboard/$projId/events',
    path: '/dashboard/$projId/events',
    getParentRoute: () => AuthdAppRoute,
  } as any)

const AuthdAppDashboardProjIdAlertsRoute =
  AuthdAppDashboardProjIdAlertsImport.update({
    id: '/dashboard/$projId/alerts',
    path: '/dashboard/$projId/alerts',
    getParentRoute: () => AuthdAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authd': {
      id: '/_authd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthdImport
      parentRoute: typeof rootRoute
    }
    '/_authd/_app': {
      id: '/_authd/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthdAppImport
      parentRoute: typeof AuthdImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutImport
      parentRoute: typeof rootRoute
    }
    '/_authd/dashboard/onboarding': {
      id: '/_authd/dashboard/onboarding'
      path: '/dashboard/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof AuthdDashboardOnboardingImport
      parentRoute: typeof AuthdImport
    }
    '/_authd/_app/dashboard/': {
      id: '/_authd/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthdAppDashboardIndexImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/alerts': {
      id: '/_authd/_app/dashboard/$projId/alerts'
      path: '/dashboard/$projId/alerts'
      fullPath: '/dashboard/$projId/alerts'
      preLoaderRoute: typeof AuthdAppDashboardProjIdAlertsImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/events': {
      id: '/_authd/_app/dashboard/$projId/events'
      path: '/dashboard/$projId/events'
      fullPath: '/dashboard/$projId/events'
      preLoaderRoute: typeof AuthdAppDashboardProjIdEventsImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/logs': {
      id: '/_authd/_app/dashboard/$projId/logs'
      path: '/dashboard/$projId/logs'
      fullPath: '/dashboard/$projId/logs'
      preLoaderRoute: typeof AuthdAppDashboardProjIdLogsImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/settings': {
      id: '/_authd/_app/dashboard/$projId/settings'
      path: '/dashboard/$projId/settings'
      fullPath: '/dashboard/$projId/settings'
      preLoaderRoute: typeof AuthdAppDashboardProjIdSettingsImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/traces': {
      id: '/_authd/_app/dashboard/$projId/traces'
      path: '/dashboard/$projId/traces'
      fullPath: '/dashboard/$projId/traces'
      preLoaderRoute: typeof AuthdAppDashboardProjIdTracesImport
      parentRoute: typeof AuthdAppImport
    }
    '/_authd/_app/dashboard/$projId/': {
      id: '/_authd/_app/dashboard/$projId/'
      path: '/dashboard/$projId'
      fullPath: '/dashboard/$projId'
      preLoaderRoute: typeof AuthdAppDashboardProjIdIndexImport
      parentRoute: typeof AuthdAppImport
    }
  }
}

// Create and export the route tree

interface AuthdAppRouteChildren {
  AuthdAppDashboardIndexRoute: typeof AuthdAppDashboardIndexRoute
  AuthdAppDashboardProjIdAlertsRoute: typeof AuthdAppDashboardProjIdAlertsRoute
  AuthdAppDashboardProjIdEventsRoute: typeof AuthdAppDashboardProjIdEventsRoute
  AuthdAppDashboardProjIdLogsRoute: typeof AuthdAppDashboardProjIdLogsRoute
  AuthdAppDashboardProjIdSettingsRoute: typeof AuthdAppDashboardProjIdSettingsRoute
  AuthdAppDashboardProjIdTracesRoute: typeof AuthdAppDashboardProjIdTracesRoute
  AuthdAppDashboardProjIdIndexRoute: typeof AuthdAppDashboardProjIdIndexRoute
}

const AuthdAppRouteChildren: AuthdAppRouteChildren = {
  AuthdAppDashboardIndexRoute: AuthdAppDashboardIndexRoute,
  AuthdAppDashboardProjIdAlertsRoute: AuthdAppDashboardProjIdAlertsRoute,
  AuthdAppDashboardProjIdEventsRoute: AuthdAppDashboardProjIdEventsRoute,
  AuthdAppDashboardProjIdLogsRoute: AuthdAppDashboardProjIdLogsRoute,
  AuthdAppDashboardProjIdSettingsRoute: AuthdAppDashboardProjIdSettingsRoute,
  AuthdAppDashboardProjIdTracesRoute: AuthdAppDashboardProjIdTracesRoute,
  AuthdAppDashboardProjIdIndexRoute: AuthdAppDashboardProjIdIndexRoute,
}

const AuthdAppRouteWithChildren = AuthdAppRoute._addFileChildren(
  AuthdAppRouteChildren,
)

interface AuthdRouteChildren {
  AuthdAppRoute: typeof AuthdAppRouteWithChildren
  AuthdDashboardOnboardingRoute: typeof AuthdDashboardOnboardingRoute
}

const AuthdRouteChildren: AuthdRouteChildren = {
  AuthdAppRoute: AuthdAppRouteWithChildren,
  AuthdDashboardOnboardingRoute: AuthdDashboardOnboardingRoute,
}

const AuthdRouteWithChildren = AuthdRoute._addFileChildren(AuthdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthdAppRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/dashboard/onboarding': typeof AuthdDashboardOnboardingRoute
  '/dashboard': typeof AuthdAppDashboardIndexRoute
  '/dashboard/$projId/alerts': typeof AuthdAppDashboardProjIdAlertsRoute
  '/dashboard/$projId/events': typeof AuthdAppDashboardProjIdEventsRoute
  '/dashboard/$projId/logs': typeof AuthdAppDashboardProjIdLogsRoute
  '/dashboard/$projId/settings': typeof AuthdAppDashboardProjIdSettingsRoute
  '/dashboard/$projId/traces': typeof AuthdAppDashboardProjIdTracesRoute
  '/dashboard/$projId': typeof AuthdAppDashboardProjIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthdAppRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/dashboard/onboarding': typeof AuthdDashboardOnboardingRoute
  '/dashboard': typeof AuthdAppDashboardIndexRoute
  '/dashboard/$projId/alerts': typeof AuthdAppDashboardProjIdAlertsRoute
  '/dashboard/$projId/events': typeof AuthdAppDashboardProjIdEventsRoute
  '/dashboard/$projId/logs': typeof AuthdAppDashboardProjIdLogsRoute
  '/dashboard/$projId/settings': typeof AuthdAppDashboardProjIdSettingsRoute
  '/dashboard/$projId/traces': typeof AuthdAppDashboardProjIdTracesRoute
  '/dashboard/$projId': typeof AuthdAppDashboardProjIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authd': typeof AuthdRouteWithChildren
  '/_authd/_app': typeof AuthdAppRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/_authd/dashboard/onboarding': typeof AuthdDashboardOnboardingRoute
  '/_authd/_app/dashboard/': typeof AuthdAppDashboardIndexRoute
  '/_authd/_app/dashboard/$projId/alerts': typeof AuthdAppDashboardProjIdAlertsRoute
  '/_authd/_app/dashboard/$projId/events': typeof AuthdAppDashboardProjIdEventsRoute
  '/_authd/_app/dashboard/$projId/logs': typeof AuthdAppDashboardProjIdLogsRoute
  '/_authd/_app/dashboard/$projId/settings': typeof AuthdAppDashboardProjIdSettingsRoute
  '/_authd/_app/dashboard/$projId/traces': typeof AuthdAppDashboardProjIdTracesRoute
  '/_authd/_app/dashboard/$projId/': typeof AuthdAppDashboardProjIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/dashboard/onboarding'
    | '/dashboard'
    | '/dashboard/$projId/alerts'
    | '/dashboard/$projId/events'
    | '/dashboard/$projId/logs'
    | '/dashboard/$projId/settings'
    | '/dashboard/$projId/traces'
    | '/dashboard/$projId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/dashboard/onboarding'
    | '/dashboard'
    | '/dashboard/$projId/alerts'
    | '/dashboard/$projId/events'
    | '/dashboard/$projId/logs'
    | '/dashboard/$projId/settings'
    | '/dashboard/$projId/traces'
    | '/dashboard/$projId'
  id:
    | '__root__'
    | '/'
    | '/_authd'
    | '/_authd/_app'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/_authd/dashboard/onboarding'
    | '/_authd/_app/dashboard/'
    | '/_authd/_app/dashboard/$projId/alerts'
    | '/_authd/_app/dashboard/$projId/events'
    | '/_authd/_app/dashboard/$projId/logs'
    | '/_authd/_app/dashboard/$projId/settings'
    | '/_authd/_app/dashboard/$projId/traces'
    | '/_authd/_app/dashboard/$projId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthdRoute: typeof AuthdRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthdRoute: AuthdRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authd",
        "/auth/sign-in",
        "/auth/sign-out"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authd": {
      "filePath": "_authd.tsx",
      "children": [
        "/_authd/_app",
        "/_authd/dashboard/onboarding"
      ]
    },
    "/_authd/_app": {
      "filePath": "_authd/_app.tsx",
      "parent": "/_authd",
      "children": [
        "/_authd/_app/dashboard/",
        "/_authd/_app/dashboard/$projId/alerts",
        "/_authd/_app/dashboard/$projId/events",
        "/_authd/_app/dashboard/$projId/logs",
        "/_authd/_app/dashboard/$projId/settings",
        "/_authd/_app/dashboard/$projId/traces",
        "/_authd/_app/dashboard/$projId/"
      ]
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-out": {
      "filePath": "auth/sign-out.tsx"
    },
    "/_authd/dashboard/onboarding": {
      "filePath": "_authd/dashboard.onboarding.tsx",
      "parent": "/_authd"
    },
    "/_authd/_app/dashboard/": {
      "filePath": "_authd/_app.dashboard/index.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/alerts": {
      "filePath": "_authd/_app.dashboard/$projId.alerts.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/events": {
      "filePath": "_authd/_app.dashboard/$projId.events.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/logs": {
      "filePath": "_authd/_app.dashboard/$projId.logs.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/settings": {
      "filePath": "_authd/_app.dashboard/$projId.settings.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/traces": {
      "filePath": "_authd/_app.dashboard/$projId.traces.tsx",
      "parent": "/_authd/_app"
    },
    "/_authd/_app/dashboard/$projId/": {
      "filePath": "_authd/_app.dashboard/$projId.index.tsx",
      "parent": "/_authd/_app"
    }
  }
}
ROUTE_MANIFEST_END */
