/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthdImport } from './routes/_authd'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthdOrgSlugOnboardingImport } from './routes/_authd/$orgSlug/_onboarding'
import { Route as AuthdOrgSlugOnboardingIndexImport } from './routes/_authd/$orgSlug/_onboarding/index'
import { Route as AuthdOrgSlugOnboardingOnboardingImport } from './routes/_authd/$orgSlug/_onboarding/onboarding'
import { Route as AuthdOrgSlugProjSlugDashboardImport } from './routes/_authd/$orgSlug/$projSlug/_dashboard'
import { Route as AuthdOrgSlugProjSlugDashboardIndexImport } from './routes/_authd/$orgSlug/$projSlug/_dashboard/index'
import { Route as AuthdOrgSlugProjSlugDashboardTestImport } from './routes/_authd/$orgSlug/$projSlug/_dashboard/test'
import { Route as AuthdOrgSlugProjSlugDashboardSettingsImport } from './routes/_authd/$orgSlug/$projSlug/_dashboard/settings'

// Create Virtual Routes

const AuthdOrgSlugImport = createFileRoute('/_authd/$orgSlug')()
const AuthdOrgSlugProjSlugImport = createFileRoute(
  '/_authd/$orgSlug/$projSlug',
)()

// Create/Update Routes

const AuthdRoute = AuthdImport.update({
  id: '/_authd',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthdOrgSlugRoute = AuthdOrgSlugImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthdRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)

const AuthdOrgSlugProjSlugRoute = AuthdOrgSlugProjSlugImport.update({
  id: '/$projSlug',
  path: '/$projSlug',
  getParentRoute: () => AuthdOrgSlugRoute,
} as any)

const AuthdOrgSlugOnboardingRoute = AuthdOrgSlugOnboardingImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthdOrgSlugRoute,
} as any)

const AuthdOrgSlugOnboardingIndexRoute =
  AuthdOrgSlugOnboardingIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthdOrgSlugOnboardingRoute,
  } as any)

const AuthdOrgSlugOnboardingOnboardingRoute =
  AuthdOrgSlugOnboardingOnboardingImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthdOrgSlugOnboardingRoute,
  } as any)

const AuthdOrgSlugProjSlugDashboardRoute =
  AuthdOrgSlugProjSlugDashboardImport.update({
    id: '/_dashboard',
    getParentRoute: () => AuthdOrgSlugProjSlugRoute,
  } as any)

const AuthdOrgSlugProjSlugDashboardIndexRoute =
  AuthdOrgSlugProjSlugDashboardIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthdOrgSlugProjSlugDashboardRoute,
  } as any)

const AuthdOrgSlugProjSlugDashboardTestRoute =
  AuthdOrgSlugProjSlugDashboardTestImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthdOrgSlugProjSlugDashboardRoute,
  } as any)

const AuthdOrgSlugProjSlugDashboardSettingsRoute =
  AuthdOrgSlugProjSlugDashboardSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthdOrgSlugProjSlugDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authd': {
      id: '/_authd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_authd/$orgSlug': {
      id: '/_authd/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthdOrgSlugImport
      parentRoute: typeof AuthdImport
    }
    '/_authd/$orgSlug/_onboarding': {
      id: '/_authd/$orgSlug/_onboarding'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthdOrgSlugOnboardingImport
      parentRoute: typeof AuthdOrgSlugRoute
    }
    '/_authd/$orgSlug/$projSlug': {
      id: '/_authd/$orgSlug/$projSlug'
      path: '/$projSlug'
      fullPath: '/$orgSlug/$projSlug'
      preLoaderRoute: typeof AuthdOrgSlugProjSlugImport
      parentRoute: typeof AuthdOrgSlugImport
    }
    '/_authd/$orgSlug/$projSlug/_dashboard': {
      id: '/_authd/$orgSlug/$projSlug/_dashboard'
      path: '/$projSlug'
      fullPath: '/$orgSlug/$projSlug'
      preLoaderRoute: typeof AuthdOrgSlugProjSlugDashboardImport
      parentRoute: typeof AuthdOrgSlugProjSlugRoute
    }
    '/_authd/$orgSlug/_onboarding/onboarding': {
      id: '/_authd/$orgSlug/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/$orgSlug/onboarding'
      preLoaderRoute: typeof AuthdOrgSlugOnboardingOnboardingImport
      parentRoute: typeof AuthdOrgSlugOnboardingImport
    }
    '/_authd/$orgSlug/_onboarding/': {
      id: '/_authd/$orgSlug/_onboarding/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof AuthdOrgSlugOnboardingIndexImport
      parentRoute: typeof AuthdOrgSlugOnboardingImport
    }
    '/_authd/$orgSlug/$projSlug/_dashboard/settings': {
      id: '/_authd/$orgSlug/$projSlug/_dashboard/settings'
      path: '/settings'
      fullPath: '/$orgSlug/$projSlug/settings'
      preLoaderRoute: typeof AuthdOrgSlugProjSlugDashboardSettingsImport
      parentRoute: typeof AuthdOrgSlugProjSlugDashboardImport
    }
    '/_authd/$orgSlug/$projSlug/_dashboard/test': {
      id: '/_authd/$orgSlug/$projSlug/_dashboard/test'
      path: '/test'
      fullPath: '/$orgSlug/$projSlug/test'
      preLoaderRoute: typeof AuthdOrgSlugProjSlugDashboardTestImport
      parentRoute: typeof AuthdOrgSlugProjSlugDashboardImport
    }
    '/_authd/$orgSlug/$projSlug/_dashboard/': {
      id: '/_authd/$orgSlug/$projSlug/_dashboard/'
      path: '/'
      fullPath: '/$orgSlug/$projSlug/'
      preLoaderRoute: typeof AuthdOrgSlugProjSlugDashboardIndexImport
      parentRoute: typeof AuthdOrgSlugProjSlugDashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthdOrgSlugOnboardingRouteChildren {
  AuthdOrgSlugOnboardingOnboardingRoute: typeof AuthdOrgSlugOnboardingOnboardingRoute
  AuthdOrgSlugOnboardingIndexRoute: typeof AuthdOrgSlugOnboardingIndexRoute
}

const AuthdOrgSlugOnboardingRouteChildren: AuthdOrgSlugOnboardingRouteChildren =
  {
    AuthdOrgSlugOnboardingOnboardingRoute:
      AuthdOrgSlugOnboardingOnboardingRoute,
    AuthdOrgSlugOnboardingIndexRoute: AuthdOrgSlugOnboardingIndexRoute,
  }

const AuthdOrgSlugOnboardingRouteWithChildren =
  AuthdOrgSlugOnboardingRoute._addFileChildren(
    AuthdOrgSlugOnboardingRouteChildren,
  )

interface AuthdOrgSlugProjSlugDashboardRouteChildren {
  AuthdOrgSlugProjSlugDashboardSettingsRoute: typeof AuthdOrgSlugProjSlugDashboardSettingsRoute
  AuthdOrgSlugProjSlugDashboardTestRoute: typeof AuthdOrgSlugProjSlugDashboardTestRoute
  AuthdOrgSlugProjSlugDashboardIndexRoute: typeof AuthdOrgSlugProjSlugDashboardIndexRoute
}

const AuthdOrgSlugProjSlugDashboardRouteChildren: AuthdOrgSlugProjSlugDashboardRouteChildren =
  {
    AuthdOrgSlugProjSlugDashboardSettingsRoute:
      AuthdOrgSlugProjSlugDashboardSettingsRoute,
    AuthdOrgSlugProjSlugDashboardTestRoute:
      AuthdOrgSlugProjSlugDashboardTestRoute,
    AuthdOrgSlugProjSlugDashboardIndexRoute:
      AuthdOrgSlugProjSlugDashboardIndexRoute,
  }

const AuthdOrgSlugProjSlugDashboardRouteWithChildren =
  AuthdOrgSlugProjSlugDashboardRoute._addFileChildren(
    AuthdOrgSlugProjSlugDashboardRouteChildren,
  )

interface AuthdOrgSlugProjSlugRouteChildren {
  AuthdOrgSlugProjSlugDashboardRoute: typeof AuthdOrgSlugProjSlugDashboardRouteWithChildren
}

const AuthdOrgSlugProjSlugRouteChildren: AuthdOrgSlugProjSlugRouteChildren = {
  AuthdOrgSlugProjSlugDashboardRoute:
    AuthdOrgSlugProjSlugDashboardRouteWithChildren,
}

const AuthdOrgSlugProjSlugRouteWithChildren =
  AuthdOrgSlugProjSlugRoute._addFileChildren(AuthdOrgSlugProjSlugRouteChildren)

interface AuthdOrgSlugRouteChildren {
  AuthdOrgSlugOnboardingRoute: typeof AuthdOrgSlugOnboardingRouteWithChildren
  AuthdOrgSlugProjSlugRoute: typeof AuthdOrgSlugProjSlugRouteWithChildren
}

const AuthdOrgSlugRouteChildren: AuthdOrgSlugRouteChildren = {
  AuthdOrgSlugOnboardingRoute: AuthdOrgSlugOnboardingRouteWithChildren,
  AuthdOrgSlugProjSlugRoute: AuthdOrgSlugProjSlugRouteWithChildren,
}

const AuthdOrgSlugRouteWithChildren = AuthdOrgSlugRoute._addFileChildren(
  AuthdOrgSlugRouteChildren,
)

interface AuthdRouteChildren {
  AuthdOrgSlugRoute: typeof AuthdOrgSlugRouteWithChildren
}

const AuthdRouteChildren: AuthdRouteChildren = {
  AuthdOrgSlugRoute: AuthdOrgSlugRouteWithChildren,
}

const AuthdRouteWithChildren = AuthdRoute._addFileChildren(AuthdRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthdRouteWithChildren
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthIndexRoute
  '/$orgSlug': typeof AuthdOrgSlugOnboardingRouteWithChildren
  '/$orgSlug/$projSlug': typeof AuthdOrgSlugProjSlugDashboardRouteWithChildren
  '/$orgSlug/onboarding': typeof AuthdOrgSlugOnboardingOnboardingRoute
  '/$orgSlug/': typeof AuthdOrgSlugOnboardingIndexRoute
  '/$orgSlug/$projSlug/settings': typeof AuthdOrgSlugProjSlugDashboardSettingsRoute
  '/$orgSlug/$projSlug/test': typeof AuthdOrgSlugProjSlugDashboardTestRoute
  '/$orgSlug/$projSlug/': typeof AuthdOrgSlugProjSlugDashboardIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthdRouteWithChildren
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof AuthIndexRoute
  '/$orgSlug': typeof AuthdOrgSlugOnboardingIndexRoute
  '/$orgSlug/$projSlug': typeof AuthdOrgSlugProjSlugDashboardIndexRoute
  '/$orgSlug/onboarding': typeof AuthdOrgSlugOnboardingOnboardingRoute
  '/$orgSlug/$projSlug/settings': typeof AuthdOrgSlugProjSlugDashboardSettingsRoute
  '/$orgSlug/$projSlug/test': typeof AuthdOrgSlugProjSlugDashboardTestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authd': typeof AuthdRouteWithChildren
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/': typeof AuthIndexRoute
  '/_authd/$orgSlug': typeof AuthdOrgSlugRouteWithChildren
  '/_authd/$orgSlug/_onboarding': typeof AuthdOrgSlugOnboardingRouteWithChildren
  '/_authd/$orgSlug/$projSlug': typeof AuthdOrgSlugProjSlugRouteWithChildren
  '/_authd/$orgSlug/$projSlug/_dashboard': typeof AuthdOrgSlugProjSlugDashboardRouteWithChildren
  '/_authd/$orgSlug/_onboarding/onboarding': typeof AuthdOrgSlugOnboardingOnboardingRoute
  '/_authd/$orgSlug/_onboarding/': typeof AuthdOrgSlugOnboardingIndexRoute
  '/_authd/$orgSlug/$projSlug/_dashboard/settings': typeof AuthdOrgSlugProjSlugDashboardSettingsRoute
  '/_authd/$orgSlug/$projSlug/_dashboard/test': typeof AuthdOrgSlugProjSlugDashboardTestRoute
  '/_authd/$orgSlug/$projSlug/_dashboard/': typeof AuthdOrgSlugProjSlugDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign-up'
    | '/'
    | '/$orgSlug'
    | '/$orgSlug/$projSlug'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/'
    | '/$orgSlug/$projSlug/settings'
    | '/$orgSlug/$projSlug/test'
    | '/$orgSlug/$projSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/sign-up'
    | '/'
    | '/$orgSlug'
    | '/$orgSlug/$projSlug'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/$projSlug/settings'
    | '/$orgSlug/$projSlug/test'
  id:
    | '__root__'
    | '/_auth'
    | '/_authd'
    | '/_auth/sign-up'
    | '/_auth/'
    | '/_authd/$orgSlug'
    | '/_authd/$orgSlug/_onboarding'
    | '/_authd/$orgSlug/$projSlug'
    | '/_authd/$orgSlug/$projSlug/_dashboard'
    | '/_authd/$orgSlug/_onboarding/onboarding'
    | '/_authd/$orgSlug/_onboarding/'
    | '/_authd/$orgSlug/$projSlug/_dashboard/settings'
    | '/_authd/$orgSlug/$projSlug/_dashboard/test'
    | '/_authd/$orgSlug/$projSlug/_dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthdRoute: typeof AuthdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthdRoute: AuthdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_authd"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/sign-up",
        "/_auth/"
      ]
    },
    "/_authd": {
      "filePath": "_authd.tsx",
      "children": [
        "/_authd/$orgSlug"
      ]
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_authd/$orgSlug": {
      "filePath": "_authd/$orgSlug",
      "parent": "/_authd",
      "children": [
        "/_authd/$orgSlug/_onboarding",
        "/_authd/$orgSlug/$projSlug"
      ]
    },
    "/_authd/$orgSlug/_onboarding": {
      "filePath": "_authd/$orgSlug/_onboarding.tsx",
      "parent": "/_authd/$orgSlug",
      "children": [
        "/_authd/$orgSlug/_onboarding/onboarding",
        "/_authd/$orgSlug/_onboarding/"
      ]
    },
    "/_authd/$orgSlug/$projSlug": {
      "filePath": "_authd/$orgSlug/$projSlug",
      "parent": "/_authd/$orgSlug",
      "children": [
        "/_authd/$orgSlug/$projSlug/_dashboard"
      ]
    },
    "/_authd/$orgSlug/$projSlug/_dashboard": {
      "filePath": "_authd/$orgSlug/$projSlug/_dashboard.tsx",
      "parent": "/_authd/$orgSlug/$projSlug",
      "children": [
        "/_authd/$orgSlug/$projSlug/_dashboard/settings",
        "/_authd/$orgSlug/$projSlug/_dashboard/test",
        "/_authd/$orgSlug/$projSlug/_dashboard/"
      ]
    },
    "/_authd/$orgSlug/_onboarding/onboarding": {
      "filePath": "_authd/$orgSlug/_onboarding/onboarding.tsx",
      "parent": "/_authd/$orgSlug/_onboarding"
    },
    "/_authd/$orgSlug/_onboarding/": {
      "filePath": "_authd/$orgSlug/_onboarding/index.tsx",
      "parent": "/_authd/$orgSlug/_onboarding"
    },
    "/_authd/$orgSlug/$projSlug/_dashboard/settings": {
      "filePath": "_authd/$orgSlug/$projSlug/_dashboard/settings.tsx",
      "parent": "/_authd/$orgSlug/$projSlug/_dashboard"
    },
    "/_authd/$orgSlug/$projSlug/_dashboard/test": {
      "filePath": "_authd/$orgSlug/$projSlug/_dashboard/test.tsx",
      "parent": "/_authd/$orgSlug/$projSlug/_dashboard"
    },
    "/_authd/$orgSlug/$projSlug/_dashboard/": {
      "filePath": "_authd/$orgSlug/$projSlug/_dashboard/index.tsx",
      "parent": "/_authd/$orgSlug/$projSlug/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
