version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: timescale/timescaledb:latest-pg15  # Use TimescaleDB image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logsicle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logsicle"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: